name: Build Docker image
on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build
        run: |
          docker buildx build \
            --platform linux/arm/v7,linux/amd64 \
            -t ${{ github.repository }}:latest .
